version: "3.7"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=game_db
      - MYSQL_USER=sys
      - MYSQL_PASSWORD=qwerty
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: always

